export interface Product {
  id: number;
  Date: string;
  RegionName: string;
  Area: string;
  AreaCode: string;
  AveragePrice: number;
  Index: number;
  IndexSA: string,
  "1m%Change": string,
  "12m%Change": string,
  "AveragePriceSA": "",
  SalesVolume: number,
  DetachedPrice: number;
  DetachedIndex: number;
  "Detached1m%Change": "",
  "Detached12m%Change": "",
  "SemiDetachedPrice": number,
  "SemiDetachedIndex": number,
  "SemiDetached1m%Change": "",
  "SemiDetached12m%Change": "",
  "TerracedPrice": number,
  "TerracedIndex": number,
  "Terraced1m%Change": "",
  "Terraced12m%Change": "",
  "FlatPrice": number,
  "FlatIndex": number,
  "Flat1m%Change": "",
  "Flat12m%Change": ""
}
